### ISSUE TITLE
프로그램 수정 건의안

### ISSUE THREAD

**Issue by wookmin** [dbseend/2023OSSL-PROJECT#6]
과목을 입력받을 때에 스터디 그룹이 가장 필요한 과목이 앞으로 가게끔 하게 미리 설명을 하는 것이 좋을 것 같습니다. 그리고 과목 입력할 때 통일성있게 띄어쓰기 없이 쓴다든지 정확히 입력해야한다든지 영어라면 대문자로만 쓰게 통일해야할 것 같습니다

**Comment by wookmin** [comment]
글 써서 addData()에 올렸습니다 !! 한 번 보고 확인해주세요 !!

**Comment by dbseend** [comment]
과목입력 이름은 한글로 띄어쓰기 없이 쓰도록 하고 스터디 그룹 만들기 할 때 필요한 과목을 검색 받아서 그걸로 만드는 거는 어떨까요?
